services:
  mysql-dned:
    build: 
      context: .
      dockerfile: Dockerfile-mysql
    container_name: dned-mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-net

  #python-app:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile-python
  #    target: development
  #  container_name: dned-backend
  #  depends_on:
  #    - mysql
  #  env_file:
  #    - .env
  #  ports:
  #    - "8000:8000"
  #  networks:
  #    - app-net
  #  volumes:
  #    - ./app:/app

volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge